CREATE TABLE IF NOT EXISTS twitter_schedule_task
(
    id                  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    added               TIMESTAMPTZ DEFAULT now(),
    guild_id            TEXT NOT NULL REFERENCES guild (id),
    channel_id          TEXT NOT NULL,
    uploader_id         TEXT NOT NULL,
    url_name            TEXT NOT NULL,
    update_interval     BIGINT NOT NULL,
    media_only          BOOLEAN DEFAULT FALSE,
    description         TEXT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS channel_id_url_name_idx ON twitter_schedule_task USING btree (channel_id, url_name);
