CREATE TABLE IF NOT EXISTS guild
(
    id           TEXT PRIMARY KEY,
    joined       TIMESTAMPTZ DEFAULT now(),
    last_updated TIMESTAMPTZ NULL,
    prefix       TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS guild_id_idx ON guild USING btree (id);

CREATE TABLE IF NOT EXISTS picture
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created      TIMESTAMPTZ DEFAULT now(),
    guild_id     TEXT NOT NULL REFERENCES guild (id),
    uploader_id  TEXT NOT NULL,
    name         TEXT NOT NULL,
    url          TEXT NOT NULL,
    tags         TEXT[]
);
CREATE UNIQUE INDEX IF NOT EXISTS picture_name_idx ON picture USING btree (guild_id, name);
CREATE INDEX IF NOT EXISTS picture_tags_idx ON picture USING gin (tags);
